name: Buid and Release PyTorch3D
on:
  pull_request:
    branches:
      - '**'

run-name: Build and release PyTorch3D by ${{ github.actor }}

jobs:
  build:
    strategy:
      matrix:
        config:
          - runner: windows-latest-l

    runs-on: ${{ matrix.config.runner }}
    steps:

      - name: Checkout PyTorch3D
        uses: actions/checkout@v4
        with:
          repository: facebookresearch/pytorch3d
          ref: v0.7.6
          fetch-depth: 1

      - name: Checkout builder repository
        uses: actions/checkout@v4
        with:
          path: _builder

      - name: Copy Pixi configuration and lock file
        shell: bash
        working-directory: ${{ github.workspace }}
        run : |
          cp _builder/pixi.toml _builder/pixi.lock ./

      - name: Install Pixi and PyTorch3D dependencies
        uses: prefix-dev/setup-pixi@v0.8.0
        with:
          pixi-version: v0.29.0
          cache: true
          # Enforce lockfile to ensure reproducibility or bail if the lock file
          # is not up to date.
          locked: true

      - name: Build and package PyTorch3D
        run: pixi run python setup.py sdist #bdist_wheel

      #          gh release upload v0.7.6 ../dist/pytorch3d-0.7.6-cp39-cp39-win_amd64.whl --repo urusgraphics/pytorch3d-builder --clobber

      - name: Upload as GitHub release
        working-directory: ${{ github.workspace }}/_builder
        shell: bash
        # skip  for now
        run: |
          gh release create v0.7.6 --repo urusgraphics/pytorch3d-builder --title "PyTorch3D v0.7.6" --notes "Prebuilt wheels for PyTorch3D v0.7.6"
          gh release upload v0.7.6 ../dist/pytorch3d-0.7.6.tar.gz --repo urusgraphics/pytorch3d-builder --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

